// Lista de sugestão pro campo "Marca" do veículo (Combobox com texto livre —
// ver VeiculosFields.tsx). Não é uma lista fechada: o operador pode digitar
// qualquer coisa que não esteja aqui, isso é só a sugestão pra agilizar o
// caso comum. Cobre as montadoras mais vendidas no Brasil + as grandes
// marcas internacionais (inclusive de luxo/esportivas e chinesas recentes),
// ordenada alfabeticamente.
export const MARCAS_VEICULO: string[] = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Baic",
  "Bentley",
  "BMW",
  "Buick",
  "BYD",
  "Cadillac",
  "CAOA Chery",
  "Changan",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Dacia",
  "Daewoo",
  "Daf",
  "Daihatsu",
  "Datsun",
  "Dodge",
  "Effa",
  "Ferrari",
  "Fiat",
  "Ford",
  "Foton",
  "GAC",
  "Geely",
  "Genesis",
  "GMC",
  "Great Wall",
  "GWM",
  "Haval",
  "Hino",
  "Honda",
  "Hyundai",
  "Infiniti",
  "International",
  "Iveco",
  "JAC",
  "Jaguar",
  "Jeep",
  "Jinbei",
  "Kia",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lifan",
  "Lincoln",
  "Lotus",
  "Man",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "RAM",
  "Renault",
  "Rolls-Royce",
  "Saab",
  "Scania",
  "Seat",
  "Škoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Troller",
  "Volkswagen",
  "Volvo",
];
